### ISSUE TITLE
METADATA WIDGET!!!!

### ISSUE THREAD

**Issue by andrewbenedictwallace** [CobwebOrg/cobweb-django#111]
# The problem
- Django is *very* opinionated, and strongly tied to a strict relational-database model.
- Cobweb should cover a variety of use cases with different metadata needs, and we have no control over imported metadata schemas.
- Django *does* have a "JSONField", to support arbitrary data structures with postgres's JSON data type type. I've been using this to store all metadata beyond "title", "description", and "keywords", *but* there aren't good HTML widgets to support this type – you get a <textarea> json, unless your write your own.

# Potential Solutions 

## 1. Be inflexible. Force users to conform to a strict, hard-coded schema. Clearly separate the imported data, which can be stored in a JSONField but not edited.

To be honest, I hadn't even been considering this option. It'd be so much easier. Maybe I'm wasting a lot of energy on things that don't add that much value...

## 2. No JSONField - use a separate table of (Object, property, value) triples.

Pros:
- Highly normalized, makes some queries easy.
- Good Django HTML widget support via [formsets](https://docs.djangoproject.com/en/2.0/topics/forms/formsets/)

Cons:
- Unnecessary layer of complexity. It just feels wrong.
- Getting the metadata involves expensive joins. Caching / indexing has to be configured to avoid this. Even more complexity.
- Increases our dependence on a dated model of web app design, makes it harder to create a modern, javascripty feel.

## 3. Write new Django FormFields and Widgets.

Pros:
- Possibly the least work.
- Allows more flexible metadata storage w/o diverging too far from Django Orthodoxy (and thus maintainability).
- Make a tool nobody's made before (a decent JSON widget!), share it w/ the world.

Cons:
- Lots of work understanding Django internals.
- Still depend on dated web app model.
- Probably there's a reason nobody's made this tool before, and ours would probably be too specific to our particular model for the JSON-formatted data to share anyway.

## 4. JavaScript option 1: make a jquery widget.

Pros:
- Django bit can stay simple, sending and receiving json.
- Fast, modern-feeling, javascripty experience.
- Can use good libraries like [Select2](https://select2.org/).

Cons:
- More complexity, with a fairly intimate connection between Python and JavaScript components.
- Still a bit dated.

## 5. Javascript option 2: make a react widget.

Cons:
- Steeper learning curve than jquery.
- Less suited to a single widget - that's possible, but react is really meant for building the whole app.

Pros:
- Stepping stone to building the whole app in react, w/ many benefits:
    - People really seem to like react. Once you get over the initial unfamiliarity with its way of doing things it's supposed to be fairly fast and easy. It actually implements a few things that had already occurred to me as better ways of making web apps.
    - Does all the rendering client-side, saving us server resources.
    - All our backend work is still useful - we can plug in the [Django REST Framework](http://www.django-rest-framework.org/) to run our API - which I was planning to do anyway.
    - Moves us toward a modern stack: NoSQL db, client-side framework, &c, each part of which has caught on for a reason. The extra learning time at least gives me something more useful than expertise in Django form internals.

Cons to switching entirely to react:
- Client-side rendering interferes with search engine indexing and can slow down the initial page load (since the whole javascript app has to load first). One solution is isomorphic Javascript - basically run our react code on the server to render the first page, then hand off to the client. That's a new layer of complexity. The Django REST Framework has a [browsable API](http://www.django-rest-framework.org/topics/browsable-api/) that might be good enough for search indexing...

# Current Status

I've made significant progress on #3 (a new Django widget), but am really leaning toward #1 (inflexible metadata) or #5 (switching to React). The middle ground options just don't seem to be worth the trouble.

I've also made some progress on the react version and it seems doable, but it'd really only be worth it if we wanted to change our frontend framework to react – which is a pretty big decision.

**Comment by broadwell** [comment]
Yeah, the BuildUCLA web team students I supervise are always agitating to burn down any existing framework we're using and replace it with a JSON bucket on the backend and whatever hotrod Javascript front-end is in vogue. Apparently this is called a "progressive" stack. I'm not against it in principle, though for this project, I think I'd prefer to get #1 working and then explore #3 or #5 if there's time.
