### ISSUE TITLE
script to create github issue for each .feature file

### ISSUE THREAD

**Issue by andrewbenedictwallace** [CobwebOrg/cobweb-django#135]
and close it if test passes? but reopen if it fails?
as test runner extension?

boilerplate to-do list:
- write scenarios (incl steps)
- implement steps in python
- implement feature so test passes

http://pygithub.readthedocs.io/en/latest/

**Comment by broadwell** [comment]
Reopening the ticket in case of test failure seems OK to me. Logically there's of course a difference between "this feature does not exist and needs to be implemented" vs. "this feature exists but just stopped working" -- but from a functional point of view, they're kind of the same.

**Comment by andrewbenedictwallace** [comment]
Although tbh we should just be rejecting any changes that break previously-passing tests. So it's probably not a scenario we need to address.
