### ISSUE TITLE
[create specific issues for thing things I'll have to do in order to] Implement basic functionality for prototype demo.

### ISSUE THREAD

**Issue by andrewbenedictwallace** [CobwebOrg/cobweb-django#26]
1. Create project.
2. Invite admins and nominators.
3. Edit project metadata.
4. Search resources.
5. Get info on a resource in someone's collection. Nominate it to my projects.
6. Get (blank) info page for a resource that isn't in any collection yet. Nominate it and edit metadata.

**Comment by broadwell** [comment]
Maybe we can break these out into separate tickets? I'd be happy to do it.

**Comment by andrewbenedictwallace** [comment]
Sure. A lot of it's already there. I was just thinking through the whole show to figure out what we need to add.

**Comment by andrewbenedictwallace** [comment]
Okay, I think the new functionality we'd need breaks down to something like:
https://github.com/CobwebOrg/cobweb-django/issues/29
https://github.com/CobwebOrg/cobweb-django/issues/30 and
https://github.com/CobwebOrg/cobweb-django/issues/31

**Comment by andrewbenedictwallace** [comment]
Which are still pretty vague and could use fleshing out, but are at least progress.
