### ISSUE TITLE
Consolidate js and css with webpack, django-webpack-loader.

### ISSUE THREAD

**Issue by andrewbenedictwallace** [CobwebOrg/cobweb-django#84]
Right now I have, for example, many versions of jquery getting loaded, and my js/css code is all over the place.

Things to consolidate:
- Bootstrap, custom sass
- Bootstrap javascript
- js and css snippets from base.html, maybe other templates?
- font-awesome
- django-autocomplete-light
- get rid of that stupid json widget that isn't good anyway
- what was the slick jquery tables app???

**Comment by broadwell** [comment]
I know this pain...

**Comment by andrewbenedictwallace** [comment]
Done for many components – including bootstrap and FontAwesome icons. Not worth it for debug toolbar and admin site.

Main holdout is django-autocomplete-light, which doesn't seem to work with the webpack-installed jquery. The solution is probably to remove it and use select2 (the js library it invokes) directly. Forking that to it's own ticket and closing this one:
https://github.com/CobwebOrg/cobweb-django/issues/87
