### ISSUE TITLE
Decrease font-size for contents of Notes

### ISSUE THREAD

**Issue by janettaylor** [CobwebOrg/cobweb-django#99]
Currently, the font-size of the contents of the Notes defaults to the <body> font-size which is .875rem.  Please decrease the font-size within the individual Notes to .8rem.  I think that could be done by assigning a font-size of .8rem to the .card-body.

This is an example of the html of the contents of a Note:

...p class="card-body p-2">Confirmed starting crawl date for description.</p...

**Comment by andrewbenedictwallace** [comment]
Done!

Added to cobweb.scss:
`.note {
  @extend .card, .border-info, .bg-white, .mb-3;
  font-size: 0.8rem;
}

.note-header {
  @extend .card-header, .bg-info, .card-title, .p-2;
}

.note-body {
  @extend .card-body, .p-2;
}

.note-warning {
  @extend .note, .border-warning;
}

.note-warning > .note-header {
  @extend .note-header, .bg-warning;
}`
